# Generated by Django 3.0.7 on 2020-06-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Endeavor', '0002_contact_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='private',
            field=models.CharField(default='N', max_length=2),
        ),
    ]
